// db/schema/contracts.ts
// Generated by the schema agent — Phase 5, US-001
// org-with-units: every record has both orgId and orgUnitId

import {
  date,
  decimal,
  pgEnum,
  pgTable,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core'

// ── Enums ────────────────────────────────────────────────────────────

export const contractStatusEnum = pgEnum('contract_status', [
  'draft',
  'pending',
  'active',
  'expired',
  'cancelled',
])

export const contractTypeEnum = pgEnum('contract_type', [
  'standard',
  'premium',
  'enterprise',
])
// Decision (2026-05-12): contractType is a fixed enum, not a lookup table.
// PM confirmed during sprint 1 planning. Revisit if types need to be
// user-configurable in a future sprint.

// ── Table ────────────────────────────────────────────────────────────

export const contracts = pgTable('contracts', {
  // Identity
  id: uuid('id').defaultRandom().primaryKey(),

  // Org scoping — org-with-units: both columns are non-null.
  // orgId  = the organisation (region in this project)
  // orgUnitId = the branch the AM belongs to
  // Canon rule: every query on this table must filter by orgId at minimum.
  orgId:     uuid('org_id').notNull(),
  orgUnitId: uuid('org_unit_id').notNull(),

  // Business fields
  accountManagerId: uuid('account_manager_id'),     // nullable on draft
  startDate:        date('start_date'),              // nullable on draft
  contractType:     contractTypeEnum('contract_type'), // nullable on draft

  // Status — set by the service only, never by the user.
  // Initial value: 'draft'. Transitions handled by dedicated service methods.
  status: contractStatusEnum('status').default('draft').notNull(),

  // Sensitive / PII — Finance sets this through a separate permission-gated flow.
  // It is EXCLUDED from all Zod schemas. See contracts.schema.ts for why.
  commissionRate: decimal('commission_rate', { precision: 5, scale: 2 }),

  // Audit timestamps — managed by the application, not the user.
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
})

// ── Inferred types ────────────────────────────────────────────────────
// Use these throughout the application — never import the raw table type.

export type Contract    = typeof contracts.$inferSelect
export type NewContract = typeof contracts.$inferInsert
