// modules/contracts/contracts.service.test.ts
// Generated by the test agent — Phase 6, US-001
//
// ALL tests fail when first committed (Phase 5 service stubs throw).
// All tests pass after Phase 7 implementation.
//
// The four org isolation tests at the bottom are REQUIRED by the canon.
// Do not delete or skip them.

import { afterEach, beforeEach, describe, expect, it } from 'vitest'

import { db } from '@/db'
import { contracts } from '@/db/schema'
import { makeOrgContext } from '@/tests/helpers/caller-context'
import { tomorrow } from '@/tests/helpers/dates'

import { contractService } from './contracts.service'
import type { CreateContractInput } from './contracts.schema'

// ── Test helpers ────────────────────────────────────────────────────

const validContractData = (): CreateContractInput => ({
  startDate:        tomorrow(),            // helper: today + 1 day, ISO date string
  accountManagerId: makeOrgContext().ctx.userId,
  contractType:     'standard' as const,
})

// ── Setup: clear between tests ────────────────────────────────────────

beforeEach(async () => {
  await db.delete(contracts)
})

afterEach(async () => {
  await db.delete(contracts)
})

// ── Core create behaviors ─────────────────────────────────────────────

describe('contractService.create', () => {

  it('creates a contract with orgId and orgUnitId from context', async () => {
    const { ctx } = makeOrgContext()

    const result = await contractService.create({
      data: validContractData(),
      ctx,
    })

    expect(result).toHaveProperty('data')
    const { data: contract } = result as { data: typeof contracts.$inferSelect }
    expect(contract.orgId).toBe(ctx.orgId)
    expect(contract.orgUnitId).toBe(ctx.orgUnitId)
  })

  it('always sets status to draft, regardless of input', async () => {
    const { ctx } = makeOrgContext()

    const result = await contractService.create({
      data: validContractData(),
      ctx,
    })

    const { data: contract } = result as { data: typeof contracts.$inferSelect }
    expect(contract.status).toBe('draft')
  })

  it('returns { error } for a past start date', async () => {
    const { ctx } = makeOrgContext()

    const result = await contractService.create({
      data: { ...validContractData(), startDate: '2020-01-01' },
      ctx,
    })

    expect(result).toHaveProperty('error')
    expect((result as { error: string }).error).toContain('past')
  })

})

describe('contractService.createDraft', () => {

  it('creates a draft with only accountManagerId provided', async () => {
    const { ctx } = makeOrgContext()

    const result = await contractService.createDraft({
      data: { accountManagerId: ctx.userId },
      ctx,
    })

    expect(result).toHaveProperty('data')
    const { data: contract } = result as { data: typeof contracts.$inferSelect }
    expect(contract.status).toBe('draft')
    expect(contract.startDate).toBeNull()
    expect(contract.contractType).toBeNull()
  })

})

describe('contractService.getById', () => {

  it('returns the contract when caller is in the same org', async () => {
    const { ctx } = makeOrgContext()

    const created = await contractService.create({
      data: validContractData(),
      ctx,
    })
    const contractId = (created as { data: { id: string } }).data.id

    const found = await contractService.getById({ contractId, ctx })
    expect(found).not.toBeNull()
    expect(found!.id).toBe(contractId)
  })

  it('returns null when contract does not exist', async () => {
    const { ctx } = makeOrgContext()
    const found = await contractService.getById({
      contractId: '00000000-0000-0000-0000-000000000000',
      ctx,
    })
    expect(found).toBeNull()
  })

})

// ── Required org isolation tests (canon mandate — do not remove) ─────
//
// These four tests verify data isolation between organizations.
// They are non-negotiable per Section 9 of the architecture canon.
// Every module must have them. They must all pass in production.

describe('contractService — org isolation (REQUIRED)', () => {

  it('cannot fetch a record from another org', async () => {
    const orgA = makeOrgContext()
    const orgB = makeOrgContext()

    const created = await contractService.create({
      data: validContractData(),
      ctx:  orgA.ctx,
    })
    const contractId = (created as { data: { id: string } }).data.id

    // orgB knows the ID (simulates a IDOR attempt) but should get null
    const found = await contractService.getById({
      contractId,
      ctx: orgB.ctx,
    })

    expect(found).toBeNull()
  })

  it('cannot update a record from another org', async () => {
    const orgA = makeOrgContext()
    const orgB = makeOrgContext()

    const created = await contractService.create({
      data: validContractData(),
      ctx:  orgA.ctx,
    })
    const contractId = (created as { data: { id: string } }).data.id

    const result = await contractService.update({
      contractId,
      data: { contractType: 'premium' },
      ctx:  orgB.ctx,
    })

    expect(result).toHaveProperty('error')
    expect((result as { error: string }).error).toBe('Contract not found')
  })

  it('cannot delete a record from another org', async () => {
    const orgA = makeOrgContext()
    const orgB = makeOrgContext()

    const created = await contractService.create({
      data: validContractData(),
      ctx:  orgA.ctx,
    })
    const contractId = (created as { data: { id: string } }).data.id

    const result = await contractService.delete({
      contractId,
      ctx: orgB.ctx,
    })

    expect(result).toHaveProperty('error')
    expect((result as { error: string }).error).toBe('Contract not found')
  })

  it('list returns only records from the requesting org', async () => {
    const orgA = makeOrgContext()
    const orgB = makeOrgContext()

    // Create 2 records for orgA, 1 for orgB
    await contractService.create({ data: validContractData(), ctx: orgA.ctx })
    await contractService.create({ data: validContractData(), ctx: orgA.ctx })
    await contractService.create({ data: validContractData(), ctx: orgB.ctx })

    const result = await contractService.listByOrg({ ctx: orgA.ctx })

    const { data } = result as { data: typeof contracts.$inferSelect[] }
    expect(data).toHaveLength(2)
    expect(data.every(r => r.orgId === orgA.ctx.orgId)).toBe(true)
  })

})
