// modules/contracts/contracts.schema.ts
// Generated by the schema agent — Phase 5, US-001
//
// Canon rule (Section 5): Zod schemas NEVER include:
//   id, orgId, orgUnitId, createdAt, updatedAt, status
// These are set by the service or database, never by the caller.
//
// commission_rate is ALSO excluded: it is a Sensitive/PII field set by
// Finance through a separate permission-gated flow (AC-011, future story).
// Including it here would allow any caller with contracts:create to set it,
// bypassing the Finance review.

import { z } from 'zod'

// ── Helpers ──────────────────────────────────────────────────────────

const futureOrToday = z.string().date().refine(
  (date) => new Date(date) >= new Date(new Date().toDateString()),
  { message: 'Start date cannot be in the past' }
)
// Note: compare against midnight today (toDateString() strips time).
// A start date of today is valid; yesterday is not.
// This refinement was fixed in Phase 6 after a test caught the bug.

const contractTypeValues = ['standard', 'premium', 'enterprise'] as const

// ── Create schema (full — for non-draft saves) ────────────────────────
// All three step-1 fields are required (AC-002).

export const createContractSchema = z.object({
  startDate:        futureOrToday,
  accountManagerId: z.string().uuid({ message: 'Invalid account manager' }),
  contractType:     z.enum(contractTypeValues),
})

// ── Create draft schema (AC-010 — all fields optional) ───────────────
// Saving as Draft does not enforce required-field validation.
// The service sets status = 'draft' regardless of which fields are filled.

export const createDraftContractSchema = createContractSchema.partial()

// ── Update schema ─────────────────────────────────────────────────────

export const updateContractSchema = createContractSchema.partial()

// ── ID schema ────────────────────────────────────────────────────────
// Used by getById, update, delete.

export const contractIdSchema = z.object({
  contractId: z.string().uuid({ message: 'Invalid contract ID' }),
})

// ── List schema ───────────────────────────────────────────────────────

export const listContractsSchema = z.object({
  page:     z.number().int().positive().default(1),
  pageSize: z.number().int().min(1).max(100).default(20),
  status:   z.enum(['draft', 'pending', 'active', 'expired', 'cancelled']).optional(),
})

// ── Inferred types ────────────────────────────────────────────────────

export type CreateContractInput      = z.infer<typeof createContractSchema>
export type CreateDraftContractInput = z.infer<typeof createDraftContractSchema>
export type UpdateContractInput      = z.infer<typeof updateContractSchema>
export type ContractIdInput          = z.infer<typeof contractIdSchema>
export type ListContractsInput       = z.infer<typeof listContractsSchema>
